sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: oe8SLrM70OKFscFU8P9D1hp+OnnZpptzmYgdV3UdHkhd81gFPcIRwuGaXnFTIm274vbvqkhWPnWWJxGXM4tiNfxgB4QoPNp4L85Z9DeZpRw3bczjHhjCOeTrVMDdS8vwryaDG2MOtSIgQ1CoeROIoLKdvfBmz+LFvrQzaBw8nUXXoXNBju//Z4bzhv5rvgd7B/faPjYQPWhvRGwtqjfsnGZuOFLuJkwJ3R1udpmUmLhKKbcwBlTWiMC4JnEiiiDv6mwFyZq+1asqCLED/2U5ukf7BKGlpAaRY8Md2EVUoxXitQ6lwq20SYOS3ywZWfh8x3ad/F9zD+Q6+tIjzWobL4pvF162BgQsfKk9jcX+mA764dCSfsiJtBWbUkm0RlYqHs7dzBJ0R36foKunT1FODUDGDK1ygxye73Sm6Mx0+6Z2lrW1R8KNRG/09R5kJPMykDunVq4cz0LPeqcT3xncGk5mQtIuVwlHzDF5sW99w0wCARWQRCT+lw8jrCLyVYWQ4PY3i1sC9mPaU4kF6I7mKXPfv5Lnnj2d2QRlZHruAxjGVhfd08gQ1d2yJCcywB3sKR7XxY2NRvrzB6xfEvsjdw+Qx250IU36l3pwEoqTvnbBm7CYaPanXDYEtn2gRcANBvQZZB2I3ufRYHVkdQN9AhMEbEjnKHhS2jdBYU2N/6w=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Ivanhoe--A-Romance_82
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy